services:
  mongodb:
    image: 'mongo:latest'
    container_name: reactive-messaging-mongodb
    environment:
      - 'MONGO_INITDB_DATABASE=messagingdb'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'